# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_ID', models.CharField(max_length=100, unique=True)),
                ('student_name', models.CharField(max_length=100, unique=True)),
                ('division', models.CharField(max_length=100)),
                ('student_class', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
