# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttable',
            name='student_class',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studenttable',
            name='student_name',
            field=models.CharField(max_length=100),
        ),
    ]
