# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20170919_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studenttable',
            name='id',
        ),
        migrations.AlterField(
            model_name='studenttable',
            name='student_ID',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
