# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 06:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20170920_1035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studenttable',
            options={'ordering': ['student_ID']},
        ),
    ]
