# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 05:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_class_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttable',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Division'),
        ),
        migrations.AlterField(
            model_name='studenttable',
            name='student_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Class'),
        ),
    ]
